from pathlib import Path
import os
"""
pdf_export.py
=============
FastAPI APIRouter: Export to PDF
Generates professional PDF reports from NLP analysis results.
Includes Strict Attorney Review Gate & Watermarking for AI documents.
"""

import io
import json
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse, Response
from pydantic import BaseModel
from typing import Optional

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT


router  = APIRouter()

# ── DB helper ──────────────────────────────────────────────────────────────────
from backend.demo1.pg import get_conn as _pg_get_conn

def get_conn(firm_id="default"):
    return _pg_get_conn(firm_id)

# ── Style helpers ──────────────────────────────────────────────────────────────
DARK   = colors.HexColor("#1a1a2e")
GOLD   = colors.HexColor("#c9a84c")
RED    = colors.HexColor("#c0392b")
GREEN  = colors.HexColor("#27ae60")
GRAY   = colors.HexColor("#7f8c8d")
LGRAY  = colors.HexColor("#ecf0f1")

def get_styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle("title", fontSize=22, textColor=DARK, fontName="Helvetica-Bold", spaceAfter=4, alignment=TA_LEFT),
        "subtitle": ParagraphStyle("subtitle", fontSize=11, textColor=GRAY, fontName="Helvetica", spaceAfter=12, alignment=TA_LEFT),
        "section": ParagraphStyle("section", fontSize=13, textColor=DARK, fontName="Helvetica-Bold", spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("body", fontSize=9, textColor=colors.black, fontName="Helvetica", spaceAfter=4, leading=14),
        "small": ParagraphStyle("small", fontSize=8, textColor=GRAY, fontName="Helvetica", spaceAfter=2),
        "label": ParagraphStyle("label", fontSize=8, textColor=GRAY, fontName="Helvetica-Bold", spaceAfter=1),
        "value": ParagraphStyle("value", fontSize=10, textColor=DARK, fontName="Helvetica-Bold", spaceAfter=4),
    }
    return styles

def risk_color(level: str):
    return {
        "critical": colors.HexColor("#c0392b"),
        "high":     colors.HexColor("#e67e22"),
        "medium":   colors.HexColor("#f39c12"),
        "low":      colors.HexColor("#27ae60"),
        "minimal":  colors.HexColor("#2980b9"),
    }.get(level, GRAY)

def make_header(story, styles, title, subtitle=None):
    story.append(Paragraph(title, styles["title"]))
    if subtitle:
        story.append(Paragraph(subtitle, styles["subtitle"]))
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD, spaceAfter=12))

def make_kv_table(data: list, col_widths=None):
    col_widths = col_widths or [2.2*inch, 4.3*inch]
    table = Table(data, colWidths=col_widths)
    table.setStyle(TableStyle([
        ("BACKGROUND",  (0,0), (0,-1), LGRAY),
        ("FONTNAME",    (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTNAME",    (1,0), (1,-1), "Helvetica"),
        ("FONTSIZE",    (0,0), (-1,-1), 9),
        ("TEXTCOLOR",   (0,0), (0,-1), DARK),
        ("ROWBACKGROUNDS", (0,0), (-1,-1), [colors.white, colors.HexColor("#f8f9fa")]),
        ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#dee2e6")),
        ("VALIGN",      (0,0), (-1,-1), "TOP"),
        ("TOPPADDING",  (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",(0,0),(-1,-1), 5),
        ("LEFTPADDING", (0,0), (-1,-1), 8),
    ]))
    return table

def make_footer_note(styles):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return Paragraph(f"Generated by NLP Text Analyzer API · {now}", styles["small"])

# ── PDF builders ───────────────────────────────────────────────────────────────

def build_analysis_pdf(analysis: dict) -> bytes:
    buf    = io.BytesIO()
    doc    = SimpleDocTemplate(buf, pagesize=LETTER, leftMargin=0.85*inch, rightMargin=0.85*inch, topMargin=0.9*inch, bottomMargin=0.9*inch)
    styles = get_styles()
    story  = []
    make_header(story, styles, "NLP Analysis Report", f"Text analysis · {datetime.now(timezone.utc).strftime('%B %d, %Y')}")
    story.append(Paragraph("Analysis Summary", styles["section"]))
    sentiment = analysis.get("sentiment", "N/A")
    score     = analysis.get("score", 0)
    data = [
        ["Sentiment",      sentiment.upper()],
        ["Confidence",     f"{round(score * 100, 1)}%"],
        ["Text Length",    f"{analysis.get('text_length', len(analysis.get('text','')))} chars"],
        ["Language",       analysis.get("language", "en").upper()],
    ]
    story.append(make_kv_table(data))
    story.append(Spacer(1, 10))
    entities = analysis.get("entities", [])
    if entities:
        story.append(Paragraph("Extracted Entities", styles["section"]))
        rows = [["Entity", "Type", "Confidence", "Salience"]]
        for e in entities[:20]:
            rows.append([e.get("text", ""), e.get("type", ""), f"{round(e.get('confidence', 0)*100, 1)}%", f"{round(e.get('salience', 0), 3)}"])
        tbl = Table(rows, colWidths=[2.5*inch, 1.2*inch, 1.2*inch, 1.2*inch])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",  (0,0), (-1,0), DARK), ("TEXTCOLOR",   (0,0), (-1,0), colors.white),
            ("FONTNAME",    (0,0), (-1,0), "Helvetica-Bold"), ("FONTSIZE",    (0,0), (-1,-1), 8),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LGRAY]), ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#dee2e6")),
            ("TOPPADDING",  (0,0), (-1,-1), 4), ("BOTTOMPADDING",(0,0),(-1,-1), 4), ("LEFTPADDING", (0,0), (-1,-1), 6),
        ]))
        story.append(tbl)
        story.append(Spacer(1, 10))
    text = analysis.get("text", "")
    if text:
        story.append(Paragraph("Source Text", styles["section"]))
        preview = text[:800] + ("..." if len(text) > 800 else "")
        story.append(Paragraph(preview, styles["body"]))
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    story.append(Spacer(1, 4))
    story.append(make_footer_note(styles))
    doc.build(story)
    return buf.getvalue()

def build_risk_pdf(risk: dict, label: str = "Document") -> bytes:
    buf    = io.BytesIO()
    doc    = SimpleDocTemplate(buf, pagesize=LETTER, leftMargin=0.85*inch, rightMargin=0.85*inch, topMargin=0.9*inch, bottomMargin=0.9*inch)
    styles = get_styles()
    story  = []
    make_header(story, styles, "Risk Assessment Report", f"{label} · {datetime.now(timezone.utc).strftime('%B %d, %Y')}")
    story.append(Paragraph("Risk Score", styles["section"]))
    level  = risk.get("level", "unknown")
    rcolor = risk_color(level)
    score  = risk.get("score", 0)
    summary_data = [
        ["Risk Score",    f"{score} / 10"], ["Risk Level",    level.upper()],
        ["Context",       risk.get("context", "general").upper()],
        ["Document Size", f"{risk.get('text_length', 0)} chars"],
    ]
    story.append(make_kv_table(summary_data))
    story.append(Spacer(1, 10))
    breakdown = risk.get("category_breakdown", {})
    if breakdown:
        story.append(Paragraph("Risk Category Breakdown", styles["section"]))
        rows = [["Category", "Score Contribution"]]
        for cat, val in sorted(breakdown.items(), key=lambda x: -x[1]):
            rows.append([cat.replace("_", " ").title(), str(val)])
        tbl = Table(rows, colWidths=[3.5*inch, 3*inch])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",  (0,0), (-1,0), DARK), ("TEXTCOLOR",   (0,0), (-1,0), colors.white),
            ("FONTNAME",    (0,0), (-1,0), "Helvetica-Bold"), ("FONTSIZE",    (0,0), (-1,-1), 9),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LGRAY]), ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#dee2e6")),
            ("TOPPADDING",  (0,0), (-1,-1), 5), ("BOTTOMPADDING",(0,0),(-1,-1), 5), ("LEFTPADDING", (0,0), (-1,-1), 8),
        ]))
        story.append(tbl)
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    story.append(Spacer(1, 4))
    story.append(make_footer_note(styles))
    doc.build(story)
    return buf.getvalue()

def build_case_pdf(case: dict, documents: list) -> bytes:
    buf    = io.BytesIO()
    doc    = SimpleDocTemplate(buf, pagesize=LETTER, leftMargin=0.85*inch, rightMargin=0.85*inch, topMargin=0.9*inch, bottomMargin=0.9*inch)
    styles = get_styles()
    story  = []
    make_header(story, styles, "Case Summary Report", f"{case.get('client_name','Unknown')} · {case.get('case_number','')}")
    story.append(Paragraph("Case Information", styles["section"]))
    data = [
        ["Case Number",  case.get("case_number", "N/A")], ["Client",       case.get("client_name", "N/A")],
        ["Court",        case.get("court", "N/A")], ["Judge",        case.get("judge", "N/A")],
        ["Status",       case.get("status", "N/A").upper()], ["Risk Level",   case.get("risk_level", "unknown").upper()],
        ["Filing Date",  case.get("filing_date", "N/A")],
    ]
    story.append(make_kv_table(data))
    story.append(Spacer(1, 10))
    desc = case.get("description", "")
    if desc:
        story.append(Paragraph("Description", styles["section"]))
        story.append(Paragraph(desc, styles["body"]))
        story.append(Spacer(1, 8))
    if documents:
        story.append(Paragraph(f"Documents ({len(documents)})", styles["section"]))
        rows = [["Document", "Source", "Sentiment", "Risk Score", "Added"]]
        for d in documents:
            rows.append([d.get("document_name", "")[:40], d.get("source", ""), d.get("sentiment", "N/A") or "N/A", str(d.get("risk_score", "N/A") or "N/A"), (d.get("created_at", "") or "")[:10]])
        tbl = Table(rows, colWidths=[2.2*inch, 0.9*inch, 0.9*inch, 0.9*inch, 1.0*inch])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",  (0,0), (-1,0), DARK), ("TEXTCOLOR",   (0,0), (-1,0), colors.white),
            ("FONTNAME",    (0,0), (-1,0), "Helvetica-Bold"), ("FONTSIZE",    (0,0), (-1,-1), 8),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LGRAY]), ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#dee2e6")),
            ("TOPPADDING",  (0,0), (-1,-1), 4), ("BOTTOMPADDING",(0,0),(-1,-1), 4), ("LEFTPADDING", (0,0), (-1,-1), 6),
        ]))
        story.append(tbl)
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    story.append(Spacer(1, 4))
    story.append(make_footer_note(styles))
    doc.build(story)
    return buf.getvalue()

# ── Routes ─────────────────────────────────────────────────────────────────────

class AnalysisExportBody(BaseModel):
    text:      str
    sentiment: Optional[str] = None
    score:     Optional[float] = None
    entities:  Optional[list] = []
    language:  Optional[str] = "en"
    label:     Optional[str] = "Analysis"

class RiskExportBody(BaseModel):
    text:    str
    context: Optional[str] = None
    label:   Optional[str] = "Document"

@router.post("/analysis")
def export_analysis_pdf(body: AnalysisExportBody):
    data = body.dict()
    data["text_length"] = len(body.text)
    pdf_bytes = build_analysis_pdf(data)
    return StreamingResponse(io.BytesIO(pdf_bytes), media_type="application/pdf", headers={"Content-Disposition": f'attachment; filename="analysis_{datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf"'})

@router.post("/risk")
def export_risk_pdf(body: RiskExportBody):
    from backend.demo1.risk_scorer import score_text
    risk = score_text(body.text, context=body.context)
    pdf_bytes = build_risk_pdf(risk, label=body.label)
    return StreamingResponse(io.BytesIO(pdf_bytes), media_type="application/pdf", headers={"Content-Disposition": f'attachment; filename="risk_report_{datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf"'})

@router.get("/case/{case_id}")
def export_case_pdf(case_id: int, request: Request):
    firm_id = getattr(request.state, "firm_id", "default")
    with get_conn(firm_id) as conn:
        case = conn.execute("SELECT * FROM cases WHERE id=%s AND deleted=0", (case_id,)).fetchone()
        if not case: raise HTTPException(404, f"Case {case_id} not found")
        docs = conn.execute("SELECT * FROM case_documents WHERE case_id=%s ORDER BY upload_date DESC", (case_id,)).fetchall()
    pdf_bytes = build_case_pdf(dict(case), [dict(d) for d in docs])
    case_num  = dict(case).get("case_number", str(case_id)).replace("/", "-")
    return StreamingResponse(io.BytesIO(pdf_bytes), media_type="application/pdf", headers={"Content-Disposition": f'attachment; filename="case_{case_num}.pdf"'})

@router.post("/intake")
def export_intake_pdf(body: dict):
    # Kept simple for intake, no watermark needed here
    return Response(content=b"Intake PDF generation placeholder", media_type="application/pdf")


